/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#f9f9ff",
        "surface-dim": "#d3daea",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eefe",
        "surface-container-high": "#e2e8f8",
        "surface-container-highest": "#dce2f3",
        "on-surface": "#151c27",
        "on-surface-variant": "#534434",
        "inverse-surface": "#2a313d",
        "inverse-on-surface": "#ebf1ff",
        "outline": "#867461",
        "outline-variant": "#d8c3ad",
        "surface-tint": "#855300",
        "primary": "#855300",
        "on-primary": "#ffffff",
        "primary-container": "#f59e0b",
        "on-primary-container": "#613b00",
        "inverse-primary": "#ffb95f",
        "secondary": "#006c49",
        "secondary-hover": "#005338",
        "on-secondary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "on-secondary-container": "#00714d",
        "tertiary": "#795900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#e0a800",
        "on-tertiary-container": "#584000",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffddb8",
        "primary-fixed-dim": "#ffb95f",
        "on-primary-fixed": "#2a1700",
        "on-primary-fixed-variant": "#653e00",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdf9f",
        "tertiary-fixed-dim": "#f9bd22",
        "on-tertiary-fixed": "#261a00",
        "on-tertiary-fixed-variant": "#5c4300",
        "background": "#f9f9ff",
        "on-background": "#151c27",
        "surface-variant": "#dce2f3"
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "48px",
        "xl": "80px",
        "container-max": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ["Manrope", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Manrope", "system-ui", "sans-serif"],
      },
      boxShadow: {
        "ambient-sm": "0 4px 24px rgba(245, 158, 11, 0.05)",
        "ambient-md": "0 8px 32px rgba(245, 158, 11, 0.08)",
        "ambient-lg": "0 16px 48px rgba(245, 158, 11, 0.12)",
        "glass": "0 8px 32px 0 rgba(133, 83, 0, 0.06)",
        "glass-elevated": "0 14px 40px 0 rgba(133, 83, 0, 0.10)",
      }
    },
  },
  plugins: [],
}
